Gemfile
Gemfile.lock

In test environment the application is not starting because of the
gem tzinfo not there and raising exceptions

Add tzinfo data gem

---

app/controllers/application_controller.rb
app/controllers/services_controller.rb
app/controllers/versions_controller.rb
app/models/metadata.rb
app/models/service.rb
config/routes.rb
spec/factories.rb
spec/requests/get_service_spec.rb

[trello card](https://trello.com/c/yTT4fhDj/983-get-latest-service-metadata-endpoint)
Very straight forward card. Return the latest endpoint to a given service.

First baisc implementation of get latest metadata

---

app/controllers/application_controller.rb
app/controllers/services_controller.rb
app/controllers/versions_controller.rb
app/serialisers/errors_serializer.rb
config/routes.rb
spec/requests/get_version_spec.rb

GET /services/:service_id/versions/:version_id
Co-authored-by: Matt Tei <matt.tei@digital.justice.gov.uk>

Add get the specific version from a service

---

app/controllers/services_controller.rb
app/serialisers/services_serializer.rb
config/routes.rb
spec/requests/get_services_from_user_spec.rb

[Trello Card](https://trello.com/c/52ix822P/1011-all-versions-for-a-given-user)
Create endpoint that returns all the services for a given user ID.

Add list services from user endpoint

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/services_controller.rb
app/controllers/versions_controller.rb
app/errors/metadata_version_not_found.rb
app/filters/authenticate_application.rb
app/serialisers/errors_serializer.rb
config/initializers/fb_jwt_auth.rb
deploy/fb-metadata-api-chart/templates/config_map.yaml
spec/rails_helper.rb
spec/requests/create_service_spec.rb
spec/requests/create_version_spec.rb
spec/requests/get_all_versions_spec.rb
spec/requests/get_latest_version_spec.rb
spec/requests/get_services_from_user_spec.rb
spec/requests/get_version_spec.rb
spec/support/authenticate_application.rb

Add exception handling of:
* record not found
* metadata version not found
* all JWT gem exceptions
Co-authored-by: Tomas Destefi tomas.destefi@digital.justice.gov.uk
Co-authored-by: Brendan Butler brendan.butler@digital.justice.gov.uk

Add v3 fb jwt auth implementation

---

deploy/fb-metadata-api-chart/templates/deployment.yaml

Refer to
https://github.com/ministryofjustice/fb-service-token-cache/pull/179 for
more information.

Add permission to the app to make requests to service token cache app

---

.circleci/config.yml
Gemfile
Gemfile.lock

Add unit tests to run on CircleCI.
Add brakeman for security scanner

Run unit tests on CircleCI

---

deploy/fb-metadata-api-chart/templates/network_policy.yaml

Make metadata api to talk with platform namespace

Make metadata api to talk with platform namespace

---

deploy/fb-metadata-api-chart/templates/network_policy.yaml

Add egress rules

---

Gemfile
Gemfile.lock
config/initializers/sentry.rb
deploy/fb-metadata-api-chart/templates/deployment.yaml
deploy/fb-metadata-api-chart/templates/secrets.yaml

Add sentry to the app

---

Makefile
README.md
bin/generate_access_token
bin/load-test
bin/wait-for-metadata-app
docker-compose.yml
scripts/seed_test_public_key.rb

[Trello](https://trello.com/c/GFvYFTdR/1033-performance-tests-for-api-metadata)
This is the load testing script for the metadata api. 
The main idea is to run this every time we need to have a sense of idea for each endpoint of the app.
Obs.: This script is agnostic of what language and platform we are using for the metadata api.

Load testing

---

Gemfile
Gemfile.lock
spec/helpers.rb
spec/rails_helper.rb
spec/support/helpers/test_helper.rb

We now publish the gem to Rubygems

Use Rubygems Metadata Presenter

---

config/initializers/sentry.rb

The trial is over. Plus it pollutes the logs so much

Remove sentry sampling

---

lib/tasks/add_uuid_to_items.rake

Forgot an each

---

lib/tasks/check_service_flow.rake

Task to check whether the current services which do not have any
branching are in the correct page order.

Check Service Flow order rake task

---

Gemfile
Gemfile.lock

Bump presenter v2.15.9

---

app/controllers/services_controller.rb

Order services for a given user alphabetically by name. In the future we
can add pagination.

Order user Services by name

---

deploy-eks/fb-metadata-api-chart/templates/deployment.yaml

Wait 10 seconds before stopping container

Add prestop lifecycle to deployments

---

.circleci/config.yml

We no longer needs these tests

Remove no branching editor acceptance tests

---

.circleci/config.yml

circleci/ images are being depreacted

Use circleci conveniance images

---

app/controllers/versions_controller.rb
app/models/metadata.rb
config/routes.rb
spec/requests/get_previous_version_spec.rb

[Trello](https://trello.com/c/rMBqTlnQ/2886-undo-redo-rails-ootb)
Adding a new API end point: previous route to the metadata api for undo-redo mechanism

Adding previous metadata to the metadata api for undo-redo

---

Gemfile
Gemfile.lock

Bump version of metadata presenter to 3.1 to support multi file upload components

Metadata presenter to 3.1

---

.circleci/config.yml

Update to use short lived ECR creds

---

.github/CODEOWNERS
Gemfile
Gemfile.lock
LICENSE

And add codeowners and license files.

Bump metadata presenter

---

.github/dependabot.yml

Reverts ministryofjustice/fb-metadata-api#696

Revert "Re-enable dependabot"
