ministryofjustice/fb-metadata-api

- docker-compose.yml
We will be using postgres 12 as the RDS instance DB so we should use the same in our docker-compose.
> Use postgres 12

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/services_controller.rb
- app/controllers/versions_controller.rb
- app/serialisers/metadata_serialiser.rb
- config/routes.rb
- spec/factories.rb
- spec/fixtures/create_service.json
- spec/fixtures/create_version.json
- spec/rails_helper.rb
- spec/requests/create_service_spec.rb
- spec/requests/create_version_spec.rb
Rails has a strong parameter mechanism that removes empty hashes and
empty arrays if they are passed in the JSON request body.
The way round this is to set the header to be `as: :json` in the spec
https://trello.com/c/a4RisjKm/982-update-service-endpoint-service-versions
> Create version api

- app/controllers/services_controller.rb
- app/controllers/versions_controller.rb
- config/routes.rb
- spec/requests/get_latest_version_spec.rb
To better show what it is exactly that is being returned we are changing the route that gets the latest service metadata to:
`GET /services/<service_id>/versions/latest`
Co-authored-by: Matt Tei <matt.tei@digital.justice.gov.uk>
> Change get latest service version route

- app/controllers/versions_controller.rb
- app/models/metadata.rb
- app/serialisers/metadata_serialiser.rb
- app/serialisers/versions_serialiser.rb
- config/routes.rb
- spec/requests/get_all_versions_spec.rb
This adds the `GET /services/<service_id>/versions` endpoint which will return a response object which contains all the version_id's and the created_at's for the given service_id.
We also removed the ActiveModel::JSON serializer because we were not actually using its' interface.
https://trello.com/c/8zPzleCN/999-get-all-versions-for-a-service-endpoint
Co-authored-by: Matt Tei <matt.tei@digital.justice.gov.uk>
> Add get all service metadata versions endpoint

- deploy/fb-metadata-api-chart/templates/config_map.yaml
- deploy/fb-metadata-api-chart/templates/deployment.yaml
- deploy/fb-metadata-api-chart/templates/secrets.yaml
The JWT authentication requires requests that the metadata API makes in the future to encode using private keys. Therefore we set the keys in the K8S config map for each environment.
> Add encoded keys to the environment

- deploy/fb-metadata-api-chart/templates/deployment.yaml
The deployment are failing on https://app.circleci.com/pipelines/github/ministryofjustice/fb-metadata-api/61/workflows/c63abb65-9754-480a-9402-e34a1e89bfe5/jobs/94
because the config map name was changed. Changing the old config map
name to the new one fix the issue
> Add the proper config map name to k8s deployment manifest

- deploy/fb-metadata-api-chart/templates/config_map.yaml
There is formbuilder-saas-test or formbuilder-saas-live
and the app should request to service token cache
test-production and live-production respectively.
> Fix service token cache name on env var

- deploy/fb-metadata-api-chart/templates/config_map.yaml
Following the cloud platform guides here:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/network-policy.html#network-policy
"To access a service in the target namespace, we won’t be able to simply use the service name anymore.
We have to use <serviceName>.<namespaceName>."
So adding the namespace and tested on test-production and it worked!
> Add namespace to service token cache url

- .circleci/config.yml
Currently the metadata api is a bit like the base adapter and only deploys out to the test environment. We may as well alert when it successfully does that
> Alert on successful deployment to Test

- app/controllers/application_controller.rb
- app/controllers/services_controller.rb
- app/controllers/versions_controller.rb
- app/serialisers/errors_serializer.rb
- config/routes.rb
- spec/integration/endpoints_spec.rb
When we request a route that doesn't exist we should
return a 404 JSON response containing the message
that the requested url doesn't exist.
> Add error message when route doesn't exist

- schemas/condition/condition.json
- schemas/definition/condition.base.json
- schemas/definition/condition.boolean.json
- schemas/definition/condition.defined.json
- schemas/definition/condition.expression.json
- schemas/definition/condition.number.json
- schemas/definition/condition.text.json
- schemas/definition/condition.value_type.json
- schemas/definition/conditional.boolean.json
- schemas/definition/conditions.all.json
- schemas/definition/conditions.any.json
- schemas/definition/conditions.exactly.json
- schemas/text/text.json
- schemas/validations/validations.json
- spec/integration/endpoints_spec.rb
This adds all the referenced schemas required for text field validation. There are so many because the validation for required is a boolean condition which references a lot!
https://trello.com/c/Crwo6jqv/1124-validation-for-the-text-field-component
> Validation schemas

- config/initializers/schemas.rb
- schemas/config/meta.json
- schemas/config/service.json
- schemas/definition/link_list.json
- schemas/errors/errors.json
- schemas/link/link.json
- schemas/request/services.json
- schemas/service/base.json
- spec/fixtures/create_service.json
- spec/fixtures/create_version.json
- spec/fixtures/service.json
- spec/fixtures/version.json
- spec/integration/endpoints_spec.rb
- spec/requests/create_service_spec.rb
- spec/requests/create_version_spec.rb
These adds a lot more additional schemas that are required for rendering an error.
Also some of the schemas for the top level service and footer "meta".
We also add _id and _type to the base schema as those properties were missing.
> Migrate more top level schemas required for errors

- app/controllers/application_controller.rb
- spec/integration/endpoints_spec.rb
- spec/support/authenticate_application.rb
A 401 error is returned by a server when a request lacks the correct authentication credentials. However the 401 usually indicates that a client can try to validate again.
An example of this is when basic authentication is used to prompt for a username and a password. The initial request to the server will response with a 401 which the client will then provide a user with an opportunity to enter credentials.
This app being an API there is no such mechanism in place. There is no user to intervene should a request fail to have the valid authentication credentials. Therefore we should just return a 403 (forbidden).
[More info about 401s here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)
> Return 403 instead of 401

- Gemfile
- Gemfile.lock
- spec/requests/create_service_spec.rb
The locale property is required and therefore will be rejected by schema validation in the before filter if it is not present.
This is a result of [this PR](https://github.com/ministryofjustice/fb-metadata-presenter/pull/40) which provides a bit more context as to what triggered this change.
> Reject metadata that does not have a locale

- Gemfile
- Gemfile.lock
- app/models/service.rb
- db/migrate/20210112113821_change_service_name_to_services.rb
- db/schema.rb
- spec/integration/endpoints_spec.rb
- spec/rails_helper.rb
- spec/requests/create_service_spec.rb
- spec/serialisers/metadata_serialiser_spec.rb
We need to validate the uniqueness of the service name in the metadata API.
We had to add database cleaner because the tests were cleaning the DB after each spec which makes the uniqueness fail many times.
> Add validation of uniqueness for service name

- scripts/seed_test_public_key.rb
In production we need to pass the issuer as "editor" which
will look for encoded-public-key-editor in Redis, so we
need to change this to work in development mode.
> Change the redis key name for service token cache in dev

- Makefile
- app/controllers/services_controller.rb
- spec/requests/get_services_from_user_spec.rb
For the moment we are not going to have collaboration between users. So to ease the call on the database, as well as avoiding having to extend the join to make sure only unique services are returned, remove the table join and just use a straight forward query with created_by.
There are some instances where not downing all the containers is a bit problematic when manually testing the editor in the browser
> Return user services without using a join

- .circleci/config.yml
- lib/tasks/remove_acceptance_tests_services.rake
Currently our acceptance tests do not remove the services that they create when they run. To save RSI from constant scrolling, destroy all the services that the acceptance tests creates every morning.
This is temporary as we will tidy up after each acceptance test run in the future
> Remove acceptance tests services overnight

- .circleci/config.yml
We need to run the rake task to cleanup the acceptance tests services
inside docker in order to have access to the necessary environment
variables
> Run acceptance tests cleanup script inside docker compose

- .circleci/config.yml
- deploy/fb-metadata-api-chart/templates/remove_test_services.yaml
The job to remove acceptance test services needs to be run from inside kubernetes for it to actually have access to the right database
> Remove acceptance test services every morning

- .circleci/config.yml
We want the notification for the deployment to the live environment to be sent to slack.
> Add slack notification for confirming live deployment

- lib/tasks/remove_acceptance_tests_services.rake
The acceptance tests create services using the same logged in user
during each run.
> Use acceptance tests user ID when clearing services

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/application.rb
- config/initializers/sentry.rb
- deploy/fb-metadata-api-chart/templates/deployment.yaml
- deploy/fb-metadata-api-chart/templates/remove_test_services.yaml
- lib/tasks/remove_acceptance_tests_services.rake
SENTRY_DSN environment variable is looked for by default so need to explicitly set it.
This version of sentry uses the config flag send_default_pii to decide sensitive data to be sent. This is set to false by default. This only covers the following:
- user ip address
- user cookie
- request body
Further parameters are filtered in the Sentry configuration.
Capture exception from removal of acceptance test service rake task
As a result of having 4 different namespace environments as opposed to the regular 2 we structure our sentry projects differently.
We have 2 sentry projects per app, one for test and one for live. The test one covers anything in the test-dev, test-production and live-dev namespaces whereas live is exclusively for live-production only. Therefore it's fine to let …
> Add Sentry Configuration

- deploy/fb-metadata-api-chart/templates/deployment.yaml
PLATFORM_ENV was only used by circle during deployment but not actually
injected into the containers.
It is required for the overnight cleanup task that removes acceptance
tests services. We only want it to run in the test environment.
> Set platform environment in container

- Gemfile.lock
Version 0.3.5 was yanked
https://rubygems.org/gems/mimemagic/versions/0.3.5
> Bump mimemagic gem

- deploy/fb-metadata-api-chart/templates/remove_test_services.yaml
Just to make it a little easier to check for the status of completed
cronjobs add a label to the metatdata. Should then be possible to do
something like:
`kubectl get pods -n formbuilder-saas-test -l remove-acceptance-tests-services`
Also bump the successful job history to 1.
> Add label to acceptance test cronjob

- deploy/fb-metadata-api-chart/templates/remove_test_services.yaml
The rake task that removes the acceptance tests requires the platform
environment during its run.
> Add platform environment to cronjob

- deploy/fb-metadata-api-chart/templates/ingress.yaml
We do not want unauthorised access to the metrics endpoint. There is no need for the request to even get as far as the application.
Prometheus seems to go directly to the container instead of using the ingress.
> Deny access to metrics entrypoint

- app/controllers/services_controller.rb
This is just to make it a little easier to spot whether a 422 was return
because a service with the requested name already exists, which is
perfectly fine.
> Log service exists message

- deploy/fb-metadata-api-chart/templates/deployment.yaml
This will mean that Kubernetes waits a little longer before attempting
to check the health of the container.
This may or may not help when it comes to failing connections to the
metadata api while the containers are being restarted
> Increase initialDelaySeconds

- lib/tasks/check_service_flow_objects.rake
The service flow objects should be created automatically when a user
visits the flow page for their service.
This tasks checks that each service has had a flow object created and
that it is correct.
Since there is no branching at this time each flow object should link to
the next page at the correct index in the pages array except for the
last page which should just be an empty string
> Rake task to check service flow object creation

- .circleci/config.yml
Changes to the metadata api can also affect the functionality of the
editor. Run the editor acceptance tests after deploying to test.
Unfortunately this does add about 7 minutes onto the deploy time.
> Run Editor Acceptance tests after deploying to Test

- lib/tasks/create_service_flow_objects.rake
- lib/tasks/new_flow_page_generator.rb
Older services made use of the pages array their flow as since there was
no conditional logic the editor and runner would just traverse the array
in order.
The runner is backwards compatible and will make use of either flow
objects or an array of page objects.
This adds a task to create the flow objects from the pages
array for services that do not already use the flow objects.
There is already a before_action in the editor to do this for any user
that visits the flow page for their form. This task is a backup for
that.
> Create service flow objects rake task

- Gemfile
- Gemfile.lock
Version 2.3.2 removes the lede from the start page
Relates to [this PR](https://github.com/ministryofjustice/fb-metadata-presenter/pull/170)
> Bump to version 2.3.2

- lib/tasks/add_uuid_to_items.rake
We found out that all items that users are adding doesn't have
the UUIDs being generated so we need to generate one UUID in
case the item doesn't have to use in branching expressions.
> Add uuid to items rake task

- .circleci/config.yml
Bump the number of parallel pods to 5 as we have a lot of acceptance
tests now
> Increase parallelism for editor acceptance tests

- .circleci/config.yml
The Editor acceptance tests were updated to include exercising an
instance of the editor which has BRANCHING disabled. Update the
deployment pipeline to include those tests.
> Add no branching editor acceptance tests

- .circleci/config.yml
Update the browser tools to 1.2.4.
Also only install chrome and chromedriver as we do not need firefox and
geckodriver
> Use browser tools 1.2.4

- .circleci/config.yml
- app/controllers/health_controller.rb
- config/routes.rb
- deploy-eks/fb-metadata-api-chart/templates/deployment.yaml
- deploy-eks/fb-metadata-api-chart/templates/hpa.yaml
- deploy/fb-metadata-api-chart/templates/deployment.yaml
Add readiness endpoint to check connection to database before allowing traffic to the container
Use the fb-metadata-api-deploy repo to set configuration options
Create a rolling update strategy for deployment
Adds horizontal scaling configuration for the EKS cluster. Unfortunately we are no longer able to make any changes to the old cluster. HPA was added manually to that cluster.
Parallelise deployements
> Horizontal autoscaling

- .circleci/config.yml
Old cluster Editor is no longer running
> Remove editor acceptance tests in old cluster

- Dockerfile
- lib/tasks/migrate_ignore_concurrent.rake
We call the db migrations rake task in the dockerfile. Since we have
multiple pods starting up at the same time this means it gets called
more than once.
To stop the concurrent migrations error being thrown unecessarily add
another rake task and catch the error and ignore.
> Ignore concurrent migrations when deploying

- config/initializers/inflections.rb
Rails attempts to use singular `Item` when initialising the constant `Service::Item`, causing errors when attempting to delete Service records.
Add an inflection to by pass this default, thereby initialising the constant as `Service::Items`.
> Add Inflection for Items model

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/component_items_controller.rb
- app/controllers/metadata_controller.rb
- app/controllers/services_controller.rb
- app/controllers/versions_controller.rb
- config/routes.rb
- spec/integration/endpoints_spec.rb
- spec/integration/metadata_api_test_client.rb
- spec/requests/create_component_items_spec.rb
[Trello](https://trello.com/c/026Zl7pq/2632-autocomplete-create-post-endpoint-to-retrieve-autocomplete-data-from-metadata-db)
Endpoint: `services/:service_id/components/:component_id/items/all`
This endpoint requires the `component_id` as a param as a service can have many autocomplete components, we need to know which items belong to which component within a service.
If the POST request contains a `component_id` that already exists in the database, it will create a new record with the same `component_id`.
The `before_action` to validate a schema has been moved out of the `ApplicationController` into it's own class as the `ComponentItemsController` params does not have a 'metadata' key, and hence will fail validation for this reason.
The `validate_items` method has been created to check …
> Autocomplete POST Endpoint

- app/controllers/component_items_controller.rb
- app/serialisers/component_items_serialiser.rb
- spec/requests/create_component_items_spec.rb
- spec/serialisers/component_items_serialiser_spec.rb
- Change the response from the POST endpoint to return a JSON body and status.
- Change the argument in the ComponentItemsSerialiser from the service to the service id.
> Change autocomplete endpoint

- app/controllers/component_items_controller.rb
- app/serialisers/component_items_serialiser.rb
- config/routes.rb
- spec/integration/endpoints_spec.rb
- spec/integration/metadata_api_test_client.rb
[Trello](https://trello.com/c/DzJhe3B3/2712-autocomplete-check-already-existing-items-on-upload-modal)
To minimise the amount of data that is returned to the Editor, we decided to create a new endpoint that returns items associated with one component: `services/:service_id/components/:component_id/items`
This is something we need to cater for in the Editor, to notify users as to whether they will be overwriting their already existing items or whether their autocomplete component does not have any associated items.
On success, the endpoint returns a `200` and the items associated with the component.
On failure, the endpoint returns a `404` and an error message.
> Add GET endpoint to get items associated with a component

- Gemfile
- Gemfile.lock
- app/controllers/component_items_controller.rb
- spec/requests/create_component_items_spec.rb
This was previously failing as it was ActionController::Parameters class, the validator was unable to parse this.
> Bump presenter 2.17.15

- app/controllers/services_controller.rb
- spec/requests/get_services_spec.rb
Adds the ability for the services#index to handle a name_query paramenter to filter the returned services by name.
> Add filtering services by name to services_controller#index

- Gemfile
- Gemfile.lock
- app/controllers/component_items_controller.rb
- app/models/items.rb
- app/models/metadata.rb
- spec/factories.rb
- spec/fixtures/load_testing/service.json
- spec/integration/endpoints_spec.rb
- spec/models/metadata_spec.rb
- spec/requests/get_component_items_spec.rb
[Trello](https://trello.com/c/fdaONyWG/2863-autocomplete-metadata-api-returns-all-uploaded-items-for-a-service-instead-of-only-those-necessary)
Previously we were returning _all_ of the autocomplete items for each
component when in fact we only want the latest one.
Co-authored-by: Hellema Ibrahim <hellema.ibrahim@digital.justice.gov.uk>
> Return latest autocomplete items for each component

- app/controllers/component_items_controller.rb
- spec/requests/get_component_items_spec.rb
[Trello](https://trello.com/c/fdaONyWG/2863-autocomplete-metadata-api-returns-all-uploaded-items-for-a-service-instead-of-only-those-necessary)
Currently, when there are no items found on a service it returns an empty ActiveRecord Relation. We only want a single level array to be returned, flattening removes any empty relations.
Co-authored-by: Hellema Ibrahim <hellema.ibrahim@digital.justice.gov.uk>
> Cater for for when there are no autocomplete items in a service

- app/controllers/component_items_controller.rb
- app/models/metadata.rb
- app/serialisers/component_items_serialiser.rb
- spec/fixtures/autocomplete.json
- spec/models/metadata_spec.rb
- spec/requests/get_component_items_spec.rb
- spec/serialisers/component_items_serialiser_spec.rb
[Trello](https://trello.com/c/AQN8Fcmj/2845-autocomplete-add-versionid-column-in-autocomplete-db)
The Editor will need to log which autocomplete items were used during publishing, so we will need to return those ids and the items.
Prior to this change we would return all the items associated with an autocomplete component, this included items that were associated with a detached component. We do not want to return any unnecessary items.
This change ensures we only get items that are associated with components in the main flow of a form. Since we now rely on the grid and flow objects, we need to ensure our test metadata accurately reflects the metadata in a live form, hence
we have decided to use a fixture. The fixture contains 4 autocomplete components, one of which is detached
> Return autocomplete item ids for a service

- app/controllers/services_controller.rb
- app/serialisers/services_serializer.rb
- spec/requests/get_services_spec.rb
Not sure about the code for this change, but in order for pagination to work properly when we have a search, we need total_services to actually reflect the total number of results for the search query not the total number of all services.
> Make pagination work correctly with a search query

- .circleci/config.yml
- deploy-eks/fb-metadata-api-chart/templates/remove_test_services.yaml
- Reduce acceptance tests parallelism to 4 to see if it makes the tests less brittle
- Remove Docker version from circleci config
- Only apply the remove test services cronjob in test
> Test services cron update

- deploy-eks/fb-metadata-api-chart/templates/deployment.yaml
This adds the resource request limits configuration. The fb-metadata-api-deploy repo has it for Test and Live. If it is not there then do not set it at all.
> Add resource request limits config

- .circleci/config.yml
- brakeman.ignore
We have a EOLRuby warning that is preventing us from deploying the app to production.
This warning tells us to upgrade the app to Ruby 3.
We have now prioritised this work, so for the time being ignore this warning.
Ignoring this warning will allow us to continue deploying the app to production.
> Ignore brakeman

- Gemfile
- Gemfile.lock
We update the version of the presenter to see the update of the cookie statement expiring from now on to 60 minutes
> Upgrading Presenter version to 2.17.35

- Dockerfile
Add GOVUK env vars for GovUK Publishing component. These env vars as they are required, but we do not use them.
https://app.circleci.com/pipelines/github/ministryofjustice/fb-metadata-api/2083/workflows/d4df620c-3bb6-4244-9881-ac2da4a42c04
> Add GOVUK env vars for GovUK Publishing component

- Gemfile
- Gemfile.lock
This version of the presenter adds logic to evaluate the content conditional components.
This bump should be fine to deploy to production on the metadata api.
> Bump to presenter 3.2.1

- .circleci/config.yml
In order to release conditional content, we need to merge metadata api prior to the editor change. However the metadata api require to run the editor acceptance tests to be fully deployed to production. We update temporally the deployment pipeline to run the acceptance tests on the testable editor that has the conditional content flags on. When the editor will be merged, we will be reverting this change to run the editor acceptance tests on the main editor branch.
> Deploying metadata api editor

- .circleci/config.yml
This is to revert [#661](https://github.com/ministryofjustice/fb-metadata-api/pull/661) so we test the metadata api against the editor main branch
> Removing use to testable editor for acceptance tests

- app/controllers/versions_controller.rb
Ticket: https://trello.com/c/Qm8FlI3J
Currently the versions SQL queries are scoped by locale. As we only have English (`en`) locale, this has not been an issue so far (as that is the default), but if we change the locale in the metadata JSON to something else like Welsh (`cy`) then the queries will not return results.
This is a preliminary piece of work needed to start supporting metadata with locales other than `en`, and ensuring the metadata API returns them as usual.
In the future we may decide to support the `locale` query param. For now, as the param is not sent to the API, we default to search both locales, `en` and `cy`.
> Preliminary work for metadata welsh locale

- .circleci/config.yml
We have to pin the chrome (and therefore chromedriver) version for now so the editor ATs work, as later versions have an interaction with selenium that prevents it from finding the dialog boxes.
> Pin Chrome version
